settings.ignore_department = false

[login]
    captcha_enabled = false
    username = ["id", "j_username"]
    password = ["id", "j_password"]
  # 登录后执行的操作序列
  # type 可为: "switch_window", "maximize_window", "click", "handle_alert"
  post_login_actions = [
    { type = "handle_alert" },
    { type = "click", locator = ["xpath", "//*[@id='dd65-ddheader']"], description = "点击主菜单/导航头" },
    { type = "handle_alert" },
    { type = "switch_window" },
    { type = "maximize_window" },
    { type = "click", locator = ["xpath", "//*[@id='button-1005-btnIconEl']"], description = "关闭可能出现的弹窗", optional = true }
  ]
